- .vscode/settings.json
- client/package-lock.json
- client/package.json
- client/src/App.css
- client/src/App.js
- client/src/container/billing.js
- client/src/container/body.js
- client/src/container/browse.js
- client/src/container/landingpage.js
- client/src/container/login.js
- client/src/container/matches.js
- client/src/container/nav/Nav.js
- client/src/container/nav/NavConst.js
- client/src/container/nav/temp.css
- client/src/container/profile.js
- package-lock.json
> Navigation creation

- .gitignore
- client/.gitignore
- client/package-lock.json
- client/src/App.js
- client/src/container/body.js
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Test A
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] …
> Router fix

- .vscode/settings.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/actions/actionTypes.js
- client/src/actions/index.js
- client/src/components/Register.js
- client/src/components/RegisterEmployer.js
- client/src/components/index.js
- client/src/container/body.js
- client/src/index.js
- client/src/reducers/index.js
- package-lock.json
- package.json
- server/data/users/employer/employerRoutes.js
- server/server.js
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Test A
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I …
> Employer register

- .gitignore
- client/.gitignore
- client/src/reducers/index.js
- package-lock.json
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Test A
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have …
> re-committing package-lock

- server/data/users/employer/employerModel.js
- server/data/users/jobseekers/jobseeker.js
- server/data/users/seeker/seekerModel.js
- server/data/users/seeker/seekerRoutes.js
- server/server.js
Built basic job seeker schema according to fields in Balsamiq jobseeker profile view. Implemented routes for registering, logging in, and authenticating job seekers. Included a field called likedJobs that accepts an array of foreign keys to jobs. Should be used in conjunction with job field: "likedSeekers" to form match-determining query on submission of like from either job poster or job seeker. When match is made, match will be posted to both job match field and user like field to prevent need for time-complex and redundant match querying. …
> Basic schema and routes for seekers complete

- client/.eslintrc.js
- client/src/App.js
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Test A - navBar shows up now
> app imports cleaned up and checks for token to display navbar

- client/package-lock.json
- client/package.json
- client/src/components/employer/EmployerLogin.js
- client/src/reducers/index.js
- package-lock.json
- server/data/users/employer/employerRoutes.js
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Test A - login updates state correctly still
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made …
> Add combine reducers

- client/src/components/employer/RegisterEmployer.js
- client/src/containers/Billing.js
- client/src/containers/Body.js
- client/src/containers/Browse.js
- client/src/containers/Landingpage.js
- client/src/containers/Login.js
- client/src/containers/Matches.js
- client/src/containers/Profile.js
- client/src/containers/Register.js
- client/src/containers/nav/Nav.js
- client/src/containers/nav/NavConst.js
- client/src/containers/nav/temp.css
- client/src/reducers/loggedInEmployer.js
- client/src/reducers/loggedInJobSeeker.js
- client/src/reducers/registerEmployer.js
> add containters

- client/.eslintrc.js
- client/package-lock.json
- client/package.json
- client/src/actions/index.js
- client/src/actions/profileActions.js
- server/server.js
> added heroku url to actions and cors

- client/src/actions/index.js
- client/src/actions/profileActions.js
> added https

- server/server.js
> added https to cors

- server/data/users/employer/employerRoutes.js
> employer put route added and working

- README.md
> Backend documentation

- client/package-lock.json
- client/src/components/employer/EmployerBrowseMatches.js
- client/src/components/index.js
- client/src/containers/Browse.js
> Browse matches ui function properly, needs to be linked to backend

- server/data/jobs/dummydata.json
- server/data/jobs/jobModel.js
- server/data/jobs/jobRoutes.js
- server/data/users/employer/dummydata.json
- server/data/users/employer/employerModel.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
> Job liking routes

- client/package-lock.json
- server/data/strategies.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
> Jwt expiry

- client/src/containers/Landingpage.js
> updated image

- client/src/App.js
- client/src/actions/employerActions.js
- client/src/actions/seekerActions.js
- client/src/components/employer/EmployerBrowseMatches.js
- client/src/components/employer/EmployerProfile.js
- client/src/components/seeker/SeekerBrowseMatches.js
- client/src/components/seeker/SeekerProfile.js
- client/src/containers/Body.js
- client/src/containers/Browse.js
- client/src/containers/Matches.js
- client/src/containers/Profile.js
- client/src/containers/nav/Nav.js
- client/src/index.js
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
> Container routes

- client/src/containers/nav/Nav.js
- client/src/containers/nav/temp.css
> Navigation Updates & State/NavConst Removed

- app.js
- client/src/actions/seekerActions.js
- client/src/components/employer/BillingForm.js
- client/src/components/employer/EmployerBilling.js
- client/src/components/employer/EmployerRegister.js
- client/src/components/seeker/BillingForm.js
- client/src/components/seeker/SeekerBilling.js
- client/src/components/seeker/SeekerRegister.js
- server/data/billing/routes/billingRoutes.js
- server/data/users/employer/employerModel.js
- server/data/users/seeker/seekerModel.js
- server/server.js
`Users can now purchase things.`
> Backend credits

- client/.gitignore
- client/src/actions/actionTypes.js
- client/src/actions/index.js
- client/src/actions/jobActions.js
- client/src/components/index.js
- client/src/components/seeker/SeekerBilling.js
- client/src/components/seeker/SeekerBrowse.js
- client/src/components/seeker/SeekerBrowseJobCard.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/containers/Browse.js
- client/src/containers/Register.js
- client/src/index.js
- client/src/reducers/browseJobs.js
- client/src/reducers/index.js
- server/data/strategies.js
- server/server.js
> Browse seeker view

- client/src/components/seeker/SeekerBrowseJobCard.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/styles/browseStyles.js
BrowseJobs complete
Card complete, needs more styling
styled-components added
models are missing needed data.
> SeekerBrowse UI started

- client/src/containers/nav/Nav.js
- client/src/containers/nav/navStyles.js
routes set from '#' to according route
styles put in to /styles as styled-components
> Set routes on Nav and refactored css into styled-components

- client/src/components/employer/BillingForm.js
- client/src/components/employer/EmployerBilling.js
- client/src/components/seeker/BillingForm.js
- client/src/components/seeker/SeekerBilling.js
> Billing page renders

- client/src/containers/Matches.js
> fixed double action dispatch issue

- package-lock.json
- server/data/billing/routes/billingRoutes.js
- server/data/jobs/dummydata.json
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
> Seekers now auths employer and only returns seekers matched for skills

- server/data/strategies.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
Update seeker was invalidating token because token used email in sub field.
> update seeker email works

- client/package-lock.json
- client/src/components/seeker/SeekerRegister.js
- package-lock.json
> Bug fix register seeker

- client/src/components/employer/EmployerRegister.js
Employer register now works, but we'll have to get `api/register` to issue a proper token so that the user goes automatically to their newly registered employer.
> register works

- client/src/components/employer/EmployerProfile.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/seeker/SeekerProfile.js
- client/src/components/styles/profileStyles.js
Refactored boxes on both profiles
Changes styling
> Boxes refactored and working properly

- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
> Register token

- client/src/components/employer/EmployerUploadJob.js
- client/src/components/index.js
- client/src/containers/Body.js
- client/src/containers/UploadJobs.js
- client/src/containers/nav/Nav.js
You can now upload a job for seekers to view as an employer
> Employer upload job

- client/src/containers/nav/Nav.js
- client/src/containers/nav/navStyles.js
> navigation debugged

- client/src/containers/nav/navStyles.js
> added background color + changes

- client/package-lock.json
- client/src/App.js
- client/src/actions/index.js
- client/src/components/employer/BillingForm.js
- client/src/components/employer/EmployerRegister.js
- client/src/components/seeker/SeekerBrowseJobCard.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/seeker/SeekerRegister.js
- client/src/containers/Landingpage.js
> This clears all console warnings

- client/src/containers/nav/navStyles.js
> updated navigation flexbox to justify it to the end of the container

- client/src/actions/employerActions.js
- client/src/components/employer/EmployerRegister.js
- client/src/containers/Body.js
- client/src/containers/Landingpage.js
> fixed register token and temp fix for routes

- client/package-lock.json
- server/data/jobs/jobModel.js
- server/data/jobs/jobRoutes.js
Puts the company name and description into the jobs returned to seeker so they can render that for the purpose of browsing.
> populating companyName and description tested worked

- client/src/components/employer/EmployerUploadJob.js
- client/src/containers/Browse.js
> submit job routes to home

- client/src/components/employer/EmployerRegister.js
- client/src/components/seeker/SeekerProfile.js
- client/src/components/seeker/SeekerRegister.js
- client/src/components/styles/registerStyles.js
Refactored EmployerRegister
Refactored SeekerRegister
added styled-components for both
minor syntax correction
> Sign up refactor

- client/.eslintrc.js
- client/src/actions/employerActions.js
- client/src/components/employer/EmployerProfile.js
- client/src/components/employer/EmployerRegister.js
- client/src/reducers/loggedInEmployer.js
Bug fix: employer update was not dispatching the correct action to reducers. Also added window reload for temporary solution to form fields not updating.
> Employer profile action

- client/src/App.js
- client/src/containers/nav/Nav.js
- client/src/containers/nav/navStyles.js
Styling and formatting changes
conditional nav rendering
> Changed formatting of Nav and CreditsInfo placing

- client/src/components/employer/EmployerRegister.js
- client/src/components/seeker/SeekerRegister.js
> changed a couple reroutes

- client/src/actions/seekerActions.js
- client/src/components/seeker/SeekerRegister.js
- config.js
> added experienceStuff & educationStuff to seekerregister

- client/src/components/employer/EmployerBrowseMatches.js
- client/src/components/employer/EmployerRegister.js
- client/src/components/seeker/SeekerBrowseMatches.js
- client/src/components/seeker/SeekerRegister.js
- client/src/components/styles/registerStyles.js
- client/src/containers/LandingPage.js
- client/src/containers/Login.js
- client/src/containers/nav/Nav.js
- client/src/containers/nav/navStyles.js
> Nav bar refactor

- .eslintrc.json
- server/data/jobs/jobRoutes.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
> Spend credits

- client/.eslintrc.js
- client/src/actions/actionTypes.js
- client/src/actions/browseSeekerActions.js
- client/src/actions/index.js
- client/src/components/employer/EmployerBrowseSeekerCard.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/components/index.js
- client/src/containers/Browse.js
- client/src/reducers/browseSeekers.js
- client/src/reducers/index.js
This is adds the ability to like and browse seekers. 
**Important features either missing/need to be fixed**
1. Super and skip are not added yet
2. The job you are searching for is hardcoded as the first submitted job
3. Liking for one job, will filter the seeker for all that employer's jobs
- [] My code has been reviewed by at least one peer
> Employer browse seekers

- client/src/App.js
- client/src/actions/jobs.js
- client/src/actions/seekers.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/components/employer/EmployerBrowseView.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/seeker/SeekerBrowseView.js
- client/src/reducers/jobs.js
- client/src/reducers/seekers.js
- server/data/users/employer/dummydata.json
- server/data/users/employer/employerModel.js
- server/data/users/seeker/dummydata.json
> Dynamic browse seekers that were matched

- client/src/components/seeker/SeekerRegister.js
- client/src/components/styles/landingStyles.js
- client/src/reducers/user.js
- package-lock.json
- server/data/users/seeker/seekerRoutes.js
> Register to browse

- client/src/actions/jobs.js
- server/data/jobs/jobRoutes.js
- server/server.js
> Employer and Seeker Can Both like each other and they will be matched

- client/src/App.js
- client/src/actions/actionTypes.js
- client/src/actions/billing.js
- client/src/actions/index.js
- client/src/actions/user.js
- client/src/components/employer/BillingForm.js
- client/src/components/seeker/BillingForm.js
- client/src/components/styles/billingStyle.js
- client/src/reducers/user.js
- server/data/billing/routes/billingRoutes.js
> Billing checkout functional

- client/src/App.js
- client/src/components/employer/EmployerUploadJob.js
- client/src/components/index.js
- client/src/components/styles/browseStyles.js
- client/src/components/styles/globalStyles.js
- client/src/containers/Jobs.js
- client/src/containers/LandingPage.js
- client/src/containers/PostedJobs.js
- client/src/containers/Progress.js
- client/src/reducers/jobs.js
PostJob functioning properly
PostedJobs functioning properly
needs styling
> Employer jobs

- server/data/jobs/jobRoutes.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
- server/server.js
> Added routes for edit and delete jobs

- client/package-lock.json
- client/src/components/nav/navStyles.js
> Navigationstylesupdated

- client/src/components/employer/EmployerBrowseView.js
- client/src/components/seeker/SeekerBrowseView.js
> small change for superlike to function properly

- server/data/jobs/jobRoutes.js
- server/data/users/seeker/seekerRoutes.js
PUT request to `jobseekers/archive/:seekerId` now removes seeker from the job's `matchedSeekers` array. PUT request to `jobs/archive/:jobId` now removes job from the seeker's `matchedJobs` array.
> New routes added to remove from matches

- client/src/App.js
- client/src/components/employer/EmployerBrowseView.js
- client/src/components/nav/Nav.js
- client/src/components/nav/navStyles.js
- client/src/components/seeker/SeekerBrowseView.js
- client/src/components/styles/browseStyles.js
- client/src/components/styles/globalStyles.js
- client/src/components/styles/index.js
- client/src/components/styles/landingStyles.js
- package-lock.json
fixed nav
styled BrowseView
padding and margins sitewide
> More styles

- client/src/components/employer/EditJob.js
- server/data/jobs/jobModel.js
- server/data/jobs/jobRoutes.js
Employer can now toggle whether they want their post to be active through the job edit page. Seekers will not be able to get, render, or match for jobs that are toggled inactive.
> Employer can toggle isActive through job edit page

- client/package-lock.json
- client/src/actions/jobs.js
- client/src/actions/user.js
- client/src/components/employer/EmployerProfile.js
- client/src/components/seeker/SeekerProfile.js
- client/src/reducers/user.js
- package-lock.json
EmployerProfile dynamic
EmployerProfile info rendering properly
SeekerProfile dynamic
SeekerProfile info rendering properly
editJob success dispatch name corrected
> Dynamic profile boxes

- client/src/components/employer/EmployerBrowseView.js
- client/src/components/employer/EmployerMatches.js
- client/src/components/seeker/SeekerBrowseView.js
- client/src/components/seeker/SeekerMatches.js
> Default placeholder added

- client/package-lock.json
- client/src/App.js
- client/src/actions/actionTypes.js
- client/src/actions/billing.js
- client/src/actions/index.js
- client/src/actions/jobs.js
- client/src/actions/seekers.js
- client/src/actions/user.js
- client/src/components/ErrorModal.js
- client/src/components/employer/EmployerLogin.js
- client/src/components/employer/EmployerProfile.js
- client/src/components/nav/CreditsInfo.js
- client/src/components/nav/Nav.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/seeker/SeekerLogin.js
- client/src/components/seeker/SeekerMatches.js
- client/src/components/styles/globalStyles.js
- client/src/components/styles/index.js
- client/src/containers/PostedJobs.js
- client/src/reducers/error.js
- client/src/reducers/index.js
- client/src/reducers/user.js
- package-lock.json
- server/data/billing/routes/billingRoutes.js
- server/data/jobs/jobRoutes.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
Most successful actions now push user to the next intuitive view, and most errors produce a (very unstyled) modal that informs the user of the error. Also randomly fixed the password fields because it's not really big enough for its own branch.
> Success and failure action flows improved

- client/src/App.js
- client/src/components/employer/EditJob.js
- client/src/components/employer/EmployerMatchView.js
- client/src/components/employer/EmployerMatches.js
- client/src/components/index.js
- client/src/components/seeker/SeekerMatchView.js
- client/src/components/seeker/SeekerMatches.js
- client/src/containers/MatchView.js
EmployerMatchViewAdded
SeekerMatchViewAdded
Styling needed
> Match views

- README.md
- package.json
- server/data/jobs/jobModel.js
- server/data/jobs/jobRoutes.js
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerModel.js
- server/data/users/seeker/seekerRoutes.js
More robust implementation of archiving, with arrays for both resource types on the appropriate schema, accessible through the appropriate PUT and GET endpoints. 
> Archive makeover

- server/data/billing/constants/stripe.js
- server/data/billing/routes/billingRoutes.js
Refactored stripe, eliminated an unnecessary file, and made it so that billing works on deploy without any reconfiguration.
> refactored stripe on backend

- README.md
- client/package-lock.json
- client/src/actions/actionTypes.js
- client/src/actions/index.js
- client/src/actions/jobs.js
- client/src/actions/messages.js
- client/src/actions/seekers.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/components/employer/EmployerMatchView.js
- client/src/components/employer/EmployerMatches.js
- client/src/components/messenger/MessageCompose.js
- client/src/components/messenger/MessageHistory.js
- client/src/components/messenger/MessageSideBar.js
- client/src/components/seeker/SeekerMatchView.js
- client/src/components/seeker/SeekerMatches.js
- client/src/containers/Messenger.js
- client/src/reducers/jobs.js
- package-lock.json
- server/data/jobs/jobRoutes.js
- server/data/messages/messageModel.js
- server/data/messages/messageRoutes.js
Mach browse and match views now has functioning archive and message buttons.
> Archive message from match views

- client/package-lock.json
- client/src/App.js
- package-lock.json
Any time an employer logs in and doesn't have jobs, they are forwarded to the "Upload Jobs" interface instead of the "Browse View" interface.
> Employer Forwarded to Job Posting

- client/src/App.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/containers/PostedJobs.js
> New employer workflow

- client/src/App.js
- client/src/actions/billing.js
- client/src/actions/jobs.js
- client/src/actions/messages.js
- client/src/actions/seekers.js
- client/src/actions/user.js
- client/src/components/OneModal.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/containers/Browse.js
- client/src/reducers/index.js
- client/src/reducers/jobs.js
- client/src/reducers/modal.js
Modal now receives message from reducer in all actionTypes, so that any action can now simply dispatch a prop "modalMessage", and it will cause the OneModal component to pop up and display it. Clicking anywhere currently closes the modal.
> Match modal achieved, modals consolidated

- client/src/actions/billing.js
- client/src/actions/jobs.js
- client/src/actions/messages.js
- client/src/components/employer/EmployerBrowseSeekers.js
- client/src/components/employer/EmployerProfile.js
- client/src/components/employer/EmployerRegister.js
- client/src/components/messenger/MessageHistory.js
- client/src/components/seeker/SeekerBrowseJobs.js
- client/src/components/seeker/SeekerProfile.js
- client/src/components/seeker/SeekerRegister.js
- client/src/components/styles/index.js
- client/src/reducers/messages.js
- server/data/messages/messageModel.js
- server/data/messages/messageRoutes.js
Modals now pop up in response to all errors, as well as a few successful events like matching and successful message sending. Empty job/seeker candidates now renders a composed message with a title, paragraph body, and a button with the appropriate call to action. Posting messages now instantly updates the both the messageHistory with the recipient and the conversations "sidebar" (currently rendering on top of the container).
> Modals and forwarding

- client/public/index.html
- client/public/manifest.json
- client/src/containers/LandingPage.js
- server/server.js
> Deploy things

- client/src/components/messenger/MessageHistory.js
- client/src/components/messenger/MessageSideBar.js
- client/src/components/styles/index.js
> Messaging auto scroll

- README.md
> Changed app link

- .gitignore
- client/.gitignore
- client/package-lock.json
- client/package.json
- client/src/actions/user.js
- package-lock.json
- package.json
- server/data/users/employer/employerRoutes.js
- server/data/users/seeker/seekerRoutes.js
Fixes #148 
**_*Core Authorization System Is Compatible And Has Not Been Changed_**
> Fixed security vulnerabilities

- client/src/components/seeker/SeekerBrowseView.js
- package.json
Added the Moment library to package.json. Displayed the time since jobs were posted in the SeekerBrowseView component. Now jobseekers can see how old a posting is as they are liking and skipping.
> Display time since job posted in SeekerBrowseView
